name: Deploy to server
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: 22
          script: |
            cd ~/sites/learnquickai.com
            eval `ssh-agent -s`
            ssh-add /home/moataz/.ssh/id_github
            git pull origin main
            npm run build
            pm2 restart site